### ISSUE TITLE
Possibility for mutliple css concatenation

### ISSUE THREAD

**Issue by alaksandarjesus** [wykapedia/brackets-css-concat#2]
Is it possible for multiple css concatenation. For example
vendor.css where i shall have all vendor css files like bootstrap.css, font-awesome.css
style.css where i shall have my own styling files.

**Comment by wykapedia** [comment]
Please check out another plugin that I have created which will accomplish this for you:
https://github.com/wykapedia/brackets-clientlibs-combine

**Comment by alaksandarjesus** [comment]
Hi,


Thanks for replying.  I found it the same day and got it done. I thought I closed the issue. I apologise if not.

To add as appreciation,  you plugin keeps my project neat and clean. Thanks for keeping it open to all.


Sent from Yahoo Mail on Android
