### ISSUE TITLE
Concatenation differs based folder naming convention.

### ISSUE THREAD

**Issue by alaksandarjesus** [wykapedia/brackets-css-concat#3]
![screenshot from 2015-08-10 16 33 01](https://cloud.githubusercontent.com/assets/4712552/9170156/225bb096-3f7e-11e5-9296-327ef1443964.png)

I am working on angular based project. This is my folder structure. If i use the folder name as login or login-form, my app.js is added to the line 1.

If i use my foldername as loginForm, my loginForm.directive.js is added to line 1. 

The issue persisted only for loginForm. Not for menuBar which i made as  a trial. //omit this line if i was not clear.

Why there is change in concatenation of the files?

How will i make sure my app.js file lies in the first line?

**Comment by wykapedia** [comment]
Please attach the configuration file you were using

**Comment by alaksandarjesus** [comment]
**js.concat**

// THIS file should be placed in project root

// if true, concatenates the list of files when saving one of them or when saving this file
concatOnSave = true;

// the output path of the concatenated file, directories will be created if necessary
output = app/scripts/script.js;

// the list of files (paths relative to project root) to concatenate
-components/*.js;

**Comment by wykapedia** [comment]
I believe that once you use the wildcard, that the files are served in the default order that Brackets FileManager serves them from a directory.  That is most likely the behavior that you are seeing.

**Comment by alaksandarjesus** [comment]
I got the point of including by order in js.concat file. Thanks.
